spring:
  session:
    store-type: redis
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Ibrakhim2004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

rabbitmq:
  queue:
    name: javaquides
    json:
      name: javaquides_json
  exchange:
    name: javaquides_exchange
  routing:
    key: javaquides_routing_key
    json:
      key: javaquides_routing_json_key