name:
  service:
    geocoder:
      url: https://geocode-maps.yandex.ru/1.x?apikey=


spring:
  jwt:
    secret-key: 2B4B6250655368566D5971337336763979244226452948404D635166546A576E
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
  graphql:
    graphiql:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Ibrakhim2004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      id:
        increment: 1
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  minio:
    bucket: images
    url: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin

rabbitmq:
  queue:
    name: javaquides
    json:
      name: javaquides_json
  exchange:
    name: javaquides_exchange
  routing:
    key: javaquides_routing_key
    json:
      key: javaquides_routing_json_key


